import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/NavbarDemo";

const inter = Inter({ subsets: ["latin"] });

// Metadata is handled differently in JSX (no type annotation needed)
export const metadata = {
  title: "Check",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { // No type annotation needed
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
          <NavbarDemo />
        </div>
        {children}
      </body>
    </html>
  );
}